[package]
name = "rubbl-rxpackage"
version = "0.1.1"
authors = ["Peter Williams <peter@newton.cx>"]

[dependencies]
byteorder = "^1.1"
clap = "^2.26"
failure = "^0.1"
failure_derive = "^0.1"
itertools = "^0.8"
ndarray = "^0.12"
nom = "^4"
num-traits = "^0.2"
pbr = "^1.0"
rubbl_casatables = "^0.1.4"
rubbl_core = "^0.1"
